"""initial migration

Revision ID: 318100455109
Revises: 
Create Date: 2026-09-27 11:51:29.547381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318100455109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique display name for the user'),
    sa.Column('email', sa.String(length=150), nullable=False, comment='Login email address'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt hash of user password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = account disabled'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Most recent successful login timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ecc_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owning user ID'),
    sa.Column('public_key', sa.Text(), nullable=False, comment='PEM-encoded ECC public key'),
    sa.Column('private_key_enc', sa.Text(), nullable=False, comment='AES-256-GCM encrypted PEM private key (hex-encoded)'),
    sa.Column('kdf_salt', sa.String(length=64), nullable=False, comment='PBKDF2 salt used to derive the private-key wrapping key (hex)'),
    sa.Column('priv_nonce', sa.String(length=32), nullable=False, comment='GCM nonce used to encrypt the private key (hex, 12 bytes)'),
    sa.Column('priv_auth_tag', sa.String(length=32), nullable=False, comment='GCM authentication tag for private key encryption (hex, 16 bytes)'),
    sa.Column('curve', sa.String(length=20), nullable=False, comment='ECC curve name'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Key generation timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecc_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecc_keys_user_id'), ['user_id'], unique=True)

    op.create_table('transfers',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID transfer identifier'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='User ID of the sender'),
    sa.Column('receiver_id', sa.Integer(), nullable=False, comment='User ID of the intended recipient'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original filename before encryption'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes (plaintext)'),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True, comment='MIME type of the original file'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='UUID-based filename on disk (e.g., abc123.enc)'),
    sa.Column('plaintext_sha256', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of plaintext file for integrity check'),
    sa.Column('ephemeral_public_key', sa.Text(), nullable=False, comment='PEM-encoded ephemeral ECC public key used in ECDH'),
    sa.Column('encrypted_session_key', sa.Text(), nullable=False, comment='AES session key wrapped via ECIES (hex-encoded)'),
    sa.Column('wrap_nonce', sa.String(length=32), nullable=False, comment='GCM nonce used when encrypting the session key (hex, 12 bytes)'),
    sa.Column('wrap_auth_tag', sa.String(length=32), nullable=False, comment='GCM auth tag for session key encryption (hex, 16 bytes)'),
    sa.Column('aes_nonce', sa.String(length=32), nullable=False, comment='GCM nonce used when encrypting the file (hex, 12 bytes)'),
    sa.Column('aes_auth_tag', sa.String(length=32), nullable=False, comment='GCM auth tag for file encryption (hex, 16 bytes)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING | DOWNLOADED | FAILED'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False, comment='Transfer creation timestamp (UTC)'),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True, comment='When receiver successfully downloaded the file (UTC)'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_transfers_sent_at'))
        batch_op.drop_index(batch_op.f('ix_transfers_sender_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_receiver_id'))

    op.drop_table('transfers')
    with op.batch_alter_table('ecc_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecc_keys_user_id'))

    op.drop_table('ecc_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
